import cordonBleuImage from "../assets/images/cordon-bleu.svg";
import lumpiaImage from "../assets/images/chicken-lumpia.svg";
import lollipopImage from "../assets/images/chicken-lollipop.svg";
import wingsImage from "../assets/images/chicken-wings.svg";
import comboOneImage from "../assets/images/combo-1.svg";
import comboTwoImage from "../assets/images/combo-2.svg";

export const seedMenuItems = [
  {
    id: "item-cb",
    type: "single",
    category: "Chicken Meal",
    code: "CB",
    name: "Cordon Bleu",
    price: 69,
    image: cordonBleuImage,
    available: true,
    description:
      "Savory delight, featuring tender chicken breast stuffed with ham and cheese, breaded and fried to a golden brown perfection.",
  },
  {
    id: "item-cl",
    type: "single",
    category: "Chicken Meal",
    code: "CL",
    name: "Chicken Lumpia",
    price: 49,
    image: lumpiaImage,
    available: true,
    description:
      "Filled with savory shredded chicken and a blend of aromatic spices, all wrapped up in a crispy golden-brown pastry shell.",
  },
  {
    id: "item-clp",
    type: "single",
    category: "Chicken Meal",
    code: "CLP",
    name: "Chicken Lollipop",
    price: 59,
    image: lollipopImage,
    available: true,
    description:
      "Tender chicken wings trimmed into a fun and easy-to-eat lollipop shape, seasoned with a blend of spices, and fried to crispy perfection.",
  },
  {
    id: "item-cw",
    type: "single",
    category: "Chicken Meal",
    code: "CW",
    name: "Honey Sriracha Chicken Wings",
    price: 79,
    image: wingsImage,
    available: true,
    description:
      "Golden-brown chicken wings coated in a sticky-sweet honey glaze and sprinkled with fiery sriracha seasoning for the perfect balance of sweet and spicy.",
  },
  {
    id: "combo-1",
    type: "combo",
    category: "Chick N' Match Combo",
    code: "CM 01",
    name: "Cordon Bleu + Chicken Wings",
    price: 134,
    image: comboOneImage,
    available: true,
    description: "Rice included in every meal.",
    items: ["CB", "CW"],
  },
  {
    id: "combo-2",
    type: "combo",
    category: "Chick N' Match Combo",
    code: "CM 02",
    name: "Cordon Bleu + Chicken Lollipop",
    price: 114,
    image: comboTwoImage,
    available: true,
    description: "Rice included in every meal.",
    items: ["CB", "CLP"],
  },
  {
    id: "combo-3",
    type: "combo",
    category: "Chick N' Match Combo",
    code: "CM 03",
    name: "Cordon Bleu + Chicken Lumpia",
    price: 104,
    image: comboOneImage,
    available: true,
    description: "Rice included in every meal.",
    items: ["CB", "CL"],
  },
  {
    id: "combo-4",
    type: "combo",
    category: "Chick N' Match Combo",
    code: "CM 04",
    name: "Chicken Wings + Chicken Lollipop",
    price: 124,
    image: comboTwoImage,
    available: true,
    description: "Rice included in every meal.",
    items: ["CW", "CLP"],
  },
  {
    id: "combo-5",
    type: "combo",
    category: "Chick N' Match Combo",
    code: "CM 05",
    name: "Chicken Wings + Chicken Lumpia",
    price: 114,
    image: comboOneImage,
    available: true,
    description: "Rice included in every meal.",
    items: ["CW", "CL"],
  },
  {
    id: "combo-6",
    type: "combo",
    category: "Chick N' Match Combo",
    code: "CM 06",
    name: "Chicken Lollipop + Chicken Lumpia",
    price: 94,
    image: comboTwoImage,
    available: true,
    description: "Rice included in every meal.",
    items: ["CLP", "CL"],
  },
];
